bg:
  color: [0.2, 0.6, 0.83]
  optimization: true
kmeans:
  max_iter: 1000
  stop_threshold: 0.001
  merge_threshold: 0.01
  start_center_num: 30
  max_fragments: 140
cut_fragments: false
area_threshold: 3
save:
  init: true
  output: true
  visualize_optimization: true
  loss: true
  mle: true
print_values: false
print_gradients: false
num_iter: 1000
reddy:
  delete_freq: 100
regularization:
  number: 50.0
  type: 15.0
  depth: 30.0
split:
  delete_threshold: 0.7 # the deepest hidden layers will be deleted by this threshold
  # this defines the rejection region which this layer is over the background
  split_threshold: 3.0 # the ambiguous layers will be split by this threshold
  # the higher, the less layers will be split
  reserve_threshold: 0.3
  age_threshold: 10
seed: 42
lr:
  type: 0.02
  color: 0.0005
  order: 0.02
  triangle: 0.55
  ellipse: 0.001
  rectangle: 0.2
boundary_error: 3 # to expand the body and shrink the extra region
skip_portion: 10
layer_samples: 1
penal_samples: 400
pyramid_levels: 4

