bg:
  color: [1.0, 1.0, 1.0]
  optimization: true
kmeans:
  max_iter: 1000
  stop_threshold: 0.001
  merge_threshold: 0.008
  start_center_num: 20
  max_fragments: 20
area_threshold: 5
save:
  init: true
  output: true
  visualize_optimization: true
  loss: true
print_values: false
print_gradients: false
num_iter: 1000
regularization:
  number: 5.0
  type: 10.0
  depth: 200.0
split:
  delete_threshold: 0.95 # the deepest hidden layers will be deleted by this threshold
  # this defines the rejection region which this layer is over the background
  split_threshold: 3.5 # the ambiguous layers will be split by this threshold
  # the higher, the less layers will be split
  reserve_threshold: 0.3
  age_threshold: 10
seed: 42
lr:
  type: 0.01
  color: 0.001
  order: 0.5
  triangle: 0.2
  ellipse: 0.003
  rectangle: 0.1
boundary_error: 3 # to expand the body and shrink the extra region
skip_portion: 20
layer_samples: 1
penal_samples: 100
pyramid_levels: 4

