bg_color: [1.0, 1.0, 1.0] # if it's None, it can be optimized
kmeans:
  max_iter: 1000
  stop_threshold: 0.0001
  merge_threshold: 0.001
  start_center_num: 60
area_threshold: 5
save:
  init: true
  output: true
  visualize_optimization: true
  loss: true
print_values: false
print_gradients: false
num_iter: 600
num_tests: 20
test:
  num: 10
  w: 128
  h: 128
  shape_num: 10
seed: 42
lr:
  type: 0.01
  color: 0.0001
  order: 0.05
  triangle: 0.6
  ellipse: 0.001
  rectangle: 0.3
boundary_error: 3 # to expand the body and shrink the extra region

